# Generated by Django 4.2.11 on 2024-03-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
